/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:3592a49f917310b25d4677c5aaa123bb:dc05173254b17df37c2a879ff75344d9:cd218b0d8a0d67857663953f6670bb43$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class WizardSpriteSheet_TexturePacker
	{
		public const string Wiz_Run_001 = "Wiz_Run_001";
		public const string Wiz_Run_002 = "Wiz_Run_002";
		public const string Wiz_Run_003 = "Wiz_Run_003";
		public const string Wiz_Run_004 = "Wiz_Run_004";
		public const string Wiz_Run_005 = "Wiz_Run_005";
		public const string Wiz_Run_006 = "Wiz_Run_006";
		public const string Wiz_Run_007 = "Wiz_Run_007";
		public const string Wiz_Run_008 = "Wiz_Run_008";
		public const string Wiz_Run_009 = "Wiz_Run_009";
		public const string Wiz_Run_010 = "Wiz_Run_010";
	}
}